version: '3'

services:

#PHP Service
  php:
    build: laravel/docker/php
    container_name: php_laravel
    restart: always
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - phpmyadmin
      - redis
    networks: 
      - net

  #Nginx Service
  webserver:
    image: nginx
    container_name: nginx_laravel
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/html
      - ./my-app:/var/www/myapp
      - ./my-app/build:/usr/share/nginx/html
      - ./laravel/docker/nginx/default:/etc/nginx/conf.d/default.conf
    networks: 
      - net

  reactjs:
    build: my-app
    ports:
      - "3000:3000"
    volumes:
      - ./app/node_modules
      - ./my-app:/app
    networks:
      - net
  #MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql_laravel
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3306:3306
    networks: 
      - net
   
  #PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_laravel
    restart: always
    ports:
      - "4040:80"
    volumes:
      - /sessions
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks: 
      - net

  #Redis
  redis:
    image: redis:latest
    container_name: redis_laravel
    ports:
      - 6379:6379
    networks: 
      - net

networks: 
  net:
