version: '3'

services:
  web:
    build: docker/php
    image: laravel
    depends_on:
      - redis
      - phpmyadmin
    volumes:
     - ./:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
     - 4040:80
    volumes:
     - /sessions

volumes:
  db-data: